#!/bin/bash
#
SCRIPT_NAME="math"
SCRIPT_PREFIX="math"
SCRIPT_VERSION="0.1"
SCRIPT_DESCRIPTION="math library for bash"
SCRIPT_PACKAGE="bash_include"
SCRIPT_API="1"

math_max() {
	local _max=$1
	while ${2+true} false; do
		(( _max < $2 )) && _max=$2
		shift
	done
	echo $_max
}

math_is_int() {
	[[ "$1" =~ ^[+-]?("0"[01234567]*|[123456789][01234567890]*|"0x"[01234567890abcdefABCDEF]*)$ ]]
}

math_is_float() {
	[[ "$1" =~ ^[+-]?(("0"|[123456789][01234567890]*)("."[0123456789]*)?|"."[0123456789]*)([eE][+-]?("0"|[123456789][0123456789]*))?$ ]]
}
